//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKHotkeys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class profile1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static profile1 defaultInstance = ((profile1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new profile1())));
        
        public static profile1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_1_playpause {
            get {
                return ((string)(this["hk_1_playpause"]));
            }
            set {
                this["hk_1_playpause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_2_previous {
            get {
                return ((string)(this["hk_2_previous"]));
            }
            set {
                this["hk_2_previous"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_3_next {
            get {
                return ((string)(this["hk_3_next"]));
            }
            set {
                this["hk_3_next"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_4_add {
            get {
                return ((string)(this["hk_4_add"]));
            }
            set {
                this["hk_4_add"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_12_fromstart {
            get {
                return ((string)(this["hk_12_fromstart"]));
            }
            set {
                this["hk_12_fromstart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_5_repeat {
            get {
                return ((string)(this["hk_5_repeat"]));
            }
            set {
                this["hk_5_repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_6_play_albums {
            get {
                return ((string)(this["hk_6_play_albums"]));
            }
            set {
                this["hk_6_play_albums"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_7_play_suggestions {
            get {
                return ((string)(this["hk_7_play_suggestions"]));
            }
            set {
                this["hk_7_play_suggestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_8_play_popular {
            get {
                return ((string)(this["hk_8_play_popular"]));
            }
            set {
                this["hk_8_play_popular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int splash_time {
            get {
                return ((int)(this["splash_time"]));
            }
            set {
                this["splash_time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffffff")]
        public string splash_text {
            get {
                return ((string)(this["splash_text"]));
            }
            set {
                this["splash_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff1e323c")]
        public string splash_background {
            get {
                return ((string)(this["splash_background"]));
            }
            set {
                this["splash_background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffffff")]
        public string splash_border {
            get {
                return ((string)(this["splash_border"]));
            }
            set {
                this["splash_border"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int splash_visibility {
            get {
                return ((int)(this["splash_visibility"]));
            }
            set {
                this["splash_visibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool splash_shadow {
            get {
                return ((bool)(this["splash_shadow"]));
            }
            set {
                this["splash_shadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool splash_display_for_songs {
            get {
                return ((bool)(this["splash_display_for_songs"]));
            }
            set {
                this["splash_display_for_songs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool splash_display_for_lock {
            get {
                return ((bool)(this["splash_display_for_lock"]));
            }
            set {
                this["splash_display_for_lock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_9_download {
            get {
                return ((string)(this["hk_9_download"]));
            }
            set {
                this["hk_9_download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_10_show_current_song {
            get {
                return ((string)(this["hk_10_show_current_song"]));
            }
            set {
                this["hk_10_show_current_song"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hk_11_show_all_songs {
            get {
                return ((string)(this["hk_11_show_all_songs"]));
            }
            set {
                this["hk_11_show_all_songs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_name {
            get {
                return ((string)(this["login_name"]));
            }
            set {
                this["login_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string login_pas {
            get {
                return ((string)(this["login_pas"]));
            }
            set {
                this["login_pas"] = value;
            }
        }
    }
}
